[project]
name = "tp3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alibi-detect[tensorflow]>=0.12.0",
    "eurybia>=1.3.3",
    "jupyter-bokeh>=4.0.5",
    "keras==2.14.0",
]
